# Generated by Django 2.1.3 on 2018-11-10 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_center', models.IntegerField()),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('attention_schedule', models.TextField()),
                ('phone', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_centers', models.IntegerField()),
                ('name', models.TextField(unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HealthEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_entity', models.IntegerField()),
                ('name', models.TextField(unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MedicalSpeciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_speciality', models.IntegerField()),
                ('name', models.TextField(unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_patient', models.IntegerField()),
                ('name', models.TextField()),
                ('diagnostic', models.TextField(default='')),
                ('email', models.TextField()),
                ('phone', models.IntegerField()),
                ('birthday', models.DateTimeField()),
                ('address', models.TextField()),
                ('register_date', models.DateTimeField()),
                ('entity_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webApp.HealthEntity')),
                ('gender_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webApp.Gender')),
            ],
        ),
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_therapist', models.IntegerField()),
                ('name', models.TextField()),
                ('register_date', models.DateTimeField()),
                ('password', models.TextField()),
                ('email', models.TextField()),
                ('center_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webApp.Center')),
                ('speciality_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webApp.MedicalSpeciality')),
            ],
        ),
        migrations.CreateModel(
            name='Therapy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_therapy', models.IntegerField()),
                ('date_therapy', models.DateTimeField()),
                ('elapsed_time', models.TextField()),
                ('observations', models.TextField()),
                ('center_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webApp.Center')),
                ('therapist_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webApp.Therapist')),
            ],
        ),
    ]
